server:
  port: 3344


spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itlqxrq/springcloud-config.git #GitHub上面的git仓库自己名字
          search-paths: #搜索目录
            - springcloud-config
          force-pull: true
          username: 1007825489@qq.com
          password: xrq1314521
          skip-ssl-validation: true
      label: master #读取分支
      #启动成功后访问的路径 http://ip:3344/{label}/{application}-{profile}.yml 能访问的配置文件 就表示成功了
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka


#rabbitmq相关配置,暴露bus刷新配置的端点 SpringCloud Bus动态刷新全局广播
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'

#全局通知接口访问curl -X POST "http://localhost:3344/actuator/bus-refresh"
#局部通知接口访问curl -X POST "http://localhost:3344/actuator/bus-refresh/微服务名称:端口号"